name: Terraform - Destroy

on:
  push:
    tags:
      - "destroy-*"

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-22.04
    environment: digitalocean

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
